/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'selector',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/layouts/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'dl-background': "rgb(var(--dl-background))",
        'dl-purple': "rgb(var(--dl-purple))",
        'dl-mid-purple': "rgb(var(--dl-mid-purple))",
        'dl-light-purple': "rgb(var(--dl-light-purple))",
        'dl-black-gray': "rgb(var(--dl-black-gray))",
        'dl-dark-gray': "rgb(var(--dl-dark-gray))",
        'dl-light-gray': "rgb(var(--dl-light-gray))",
        'dl-white-gray': "rgb(var(--dl-white-gray))",
        'dl-white': "rgb(var(--dl-white))",
        'dl-neutral-white': "rgb(var(--dl-neutral-white))",
        'dl-black': "rgb(var(--dl-black))",
        'dl-red': "rgb(var(--dl-red))",
        'dl-github': "rgb(var(--dl-github))",
        'dl-frontendmentor': "rgb(var(--dl-frontendmentor))",
        'dl-twitter': "rgb(var(--dl-twitter))",
        'dl-linkedin': "rgb(var(--dl-linkedin))",
        'dl-youtube': "rgb(var(--dl-youtube))",
        'dl-facebook': "rgb(var(--dl-facebook))",
        'dl-twitch': "rgb(var(--dl-twitch))",
        'dl-devto': "rgb(var(--dl-devto))",
        'dl-codewars': "rgb(var(--dl-codewars))",
        'dl-codepen': "rgb(var(--dl-codepen))",
        'dl-freecodecamp': "rgb(var(--dl-freecodecamp))",
        'dl-gitlab': "rgb(var(--dl-gitlab))",
        'dl-hashnode': "rgb(var(--dl-hashnode))",
        'dl-stackoverflow': "rgb(var(--dl-stackoverflow))",
      },
      spacing: {},
      fontFamily: {
        instrument: "'Instrument Sans'",
      },
    },
    screens: {
      sm: '480px',
      md: '768px',
      lg: '976px',
      xl: '1440px',
    },
  },
  plugins: [],
}
